export enum AppRoutes {
  HOME = "/",
  SIGN_IN = "/sign-in",
  SIGN_UP = "/sign-up",
  DASHBOARD = "/dashboard",
  PROFILE = "/profile",
  SETTINGS = "/settings",
  NOT_FOUND = "/404",
  FORBIDDEN = "/403",
  BRANCHES = "/branches/:id",
  USERS = "/users",
  ADD_BRANCH = "/branch/new",
  EDIT_BRANCH = "/branch/:id",
  ADD_RESTAURANT = "/restaurant/new",
  EDIT_RESTAURANT = "/restaurant/:id",
  RESTAURANTS = "/restaurants",
  SWITCH_RESTAURANT = "/select-restaurant",
  SWITCH_BRANCHES = "/select-branches",
  CATEGORIES = "/categories",
  ADD_CATEGORY = "/category/new",
  EDIT_CATEGORY = "/category/:id",
  ROLES = "/roles",
  ADD_ROLE = "/role/new",
  EDIT_ROLE = "/role/:id",
}


export enum LanguagePreferences {
  DE = "de",
  EN = "en",
  FR = "fr",
  ES = "es",
  IT = "it",
  JA = "ja",
  KO = "ko",
  CNSM = "cn-sm",
  CNTR = "cn-tr",
}