/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	RootQuery:{
		roleList:{
			filter:"JSONObject"
		},
		getRoleById:{

		},
		usersList:{
			filter:"JSONObject"
		},
		RestaurantList:{
			filter:"JSONObject"
		},
		restaurant:{

		},
		RBranchList:{
			filter:"JSONObject"
		},
		getBranchById:{

		},
		getBranchByRestaurantId:{

		},
		getCategoryById:{

		},
		categoryList:{
			filter:"JSONObject"
		},
		subCategoriesList:{
			filter:"JSONObject"
		},
		getSubcategoryById:{

		},
		dishList:{
			filter:"JSONObject"
		},
		getDishById:{

		},
		getDishByCategories:{
			filter:"JSONObject"
		}
	},
	Date: `scalar.Date` as const,
	JSONObject: `scalar.JSONObject` as const,
	Time: `scalar.Time` as const,
	RootMutation:{
		createRole:{
			created_at:"Date",
			deleted_at:"Date",
			updated_at:"Date",
			permissions:"JSONObject"
		},
		updateRole:{
			created_at:"Date",
			deleted_at:"Date",
			updated_at:"Date",
			permissions:"JSONObject"
		},
		deleteRole:{

		},
		createUser:{
			dob:"Date",
			last_login_at:"Date",
			otp_expiry:"Date"
		},
		updateUser:{
			dob:"Date",
			last_login_at:"Date",
			otp_expiry:"Date"
		},
		deleteUser:{

		},
		login:{

		},
		register:{
			dob:"Date",
			last_login_at:"Date",
			otp_expiry:"Date"
		},
		createRestaurant:{

		},
		updateRestaurant:{
			created_at:"Date",
			updated_at:"Date",
			deleted_at:"Date"
		},
		createCategory:{
			created_at:"Date",
			updated_at:"Date",
			deleted_at:"Date"
		},
		updateCategory:{
			created_at:"Date",
			updated_at:"Date",
			deleted_at:"Date"
		},
		deleteCategory:{

		},
		createSubcategory:{

		},
		updateSubcategory:{
			created_at:"Date",
			updated_at:"Date",
			deleted_at:"Date"
		},
		deleteSubcategory:{

		},
		createBranch:{
			created_at:"Date",
			updated_at:"Date",
			deleted_at:"Date"
		},
		updateBranch:{
			created_at:"Date",
			updated_at:"Date",
			deleted_at:"Date"
		},
		deleteBranch:{

		},
		createDish:{
			availability_start_time:"Time",
			availability_end_time:"Time",
			created_at:"Date",
			updated_at:"Date",
			deleted_at:"Date",
			discount_start_time:"Date",
			discount_end_time:"Date",
			allergen_info:"JSONObject",
			language_tags:"JSONObject",
			name_translations:"JSONObject",
			description_translations:"JSONObject",
			fssai_info:"JSONObject",
			ingredients_options:"IngredientInput",
			customization_groups:"DCusDCustomization"
		},
		updateDish:{
			availability_start_time:"Time",
			availability_end_time:"Time",
			created_at:"Date",
			updated_at:"Date",
			deleted_at:"Date",
			discount_start_time:"Date",
			discount_end_time:"Date",
			allergen_info:"JSONObject",
			language_tags:"JSONObject",
			name_translations:"JSONObject",
			description_translations:"JSONObject",
			fssai_info:"JSONObject",
			ingredients_options:"IngredientInput",
			customization_groups:"DCusDCustomization"
		}
	},
	IngredientInput:{
		created_at:"Date",
		updated_at:"Date",
		options:"DIOptionInput"
	},
	DIOptionInput:{

	},
	DCusDCustomization:{
		options:"IDCOptionInput"
	},
	IDCOptionInput:{

	},
	ID: `scalar.ID` as const
}

export const ReturnTypes: Record<string,any> = {
	RootQuery:{
		roleList:"roleListResponse",
		getRoleById:"getRoleByIdResponse",
		usersList:"usersListResponse",
		getProfile:"getProfileResponse",
		RestaurantList:"RestaurantsResponse",
		restaurant:"RestaurantResponse",
		RBranchList:"BranchesResponse",
		getBranchById:"BranchByIdResponse",
		getBranchByRestaurantId:"getBranchesByRestaurantIdResponse",
		getCategoryById:"CategoryByIdResponse",
		categoryList:"CategoryListResponse",
		subCategoriesList:"SubCategoriesListResponse",
		getSubcategoryById:"SubCategoryByIdResponse",
		dishList:"dishListResponse",
		getDishById:"getDishByIdResponse",
		getDishByCategories:"getDishByCategoriesTypeResponse"
	},
	roleListResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Role"
	},
	Role:{
		id:"Int",
		created_at:"Date",
		deleted_at:"Date",
		updated_at:"Date",
		is_admin:"Boolean",
		name:"String",
		permissions:"JSONObject"
	},
	Date: `scalar.Date` as const,
	JSONObject: `scalar.JSONObject` as const,
	getRoleByIdResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Role"
	},
	usersListResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"usersList"
	},
	usersList:{
		count:"Int",
		rows:"User"
	},
	User:{
		id:"Int",
		username:"String",
		phone:"String",
		gender:"String",
		dob:"Date",
		aadhar_card:"String",
		pan_card:"String",
		voter_id:"String",
		first_name:"String",
		last_name:"String",
		email:"String",
		password:"String",
		role_id:"Int",
		is_active:"Boolean",
		is_verified:"Boolean",
		profile_picture:"String",
		address:"String",
		city:"String",
		state:"String",
		country:"String",
		zip_code:"Int",
		last_login_at:"Date",
		login_count:"Int",
		device_token:"String",
		wallet_balance:"Float",
		referral_code:"Int",
		referred_by:"Int",
		otp_code:"Int",
		otp_expiry:"Date",
		blocked_reason:"String",
		language_preference:"String",
		created_at:"Date",
		updated_at:"Date",
		deleted_at:"Date",
		created_by:"Int",
		updated_by:"Int",
		deleted_by:"Int",
		terms_conditions_accepted:"Boolean",
		facebook:"String",
		x:"String",
		linkedin:"String",
		instagram:"String",
		role:"Role"
	},
	getProfileResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"User"
	},
	RestaurantsResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Restaurant"
	},
	Restaurant:{
		id:"Int",
		owner_id:"Int",
		name:"String",
		slug:"String",
		description:"String",
		image:"String",
		email:"String",
		phone_number:"String",
		alternate_phone_number:"String",
		website_url:"String",
		facebook_url:"String",
		instagram_url:"String",
		gst_number:"String",
		status:"String",
		rejection_reason:"String",
		fssai_license_number:"String",
		is_chain:"Boolean",
		founded_year:"String",
		total_branches:"Int",
		cuisine_types:"String",
		tags:"String",
		average_rating:"Float",
		total_reviews:"Int",
		is_verified:"Boolean",
		approval_status:"String",
		approval_notes:"String",
		timezone:"String",
		external_integration_id:"Int",
		priority_order:"Int",
		visibility_status:"String",
		cancellation_policy:"String",
		created_at:"Date",
		updated_at:"Date",
		deleted_at:"Date",
		created_by:"Int",
		updated_by:"Int",
		deleted_by:"Int",
		account_number:"String",
		upi_id:"String",
		swift_code:"String",
		bank_name:"String",
		bank_branch:"String",
		ifsc_code:"String",
		account_holder_name:"String",
		branches:"RBranch",
		branch:"RBranch",
		owner:"User"
	},
	RBranch:{
		id:"Int",
		description:"String",
		restaurant_id:"Int",
		owner_id:"Int",
		manager_id:"Int",
		location:"String",
		longitude:"Float",
		latitude:"Float",
		image:"String",
		email:"String",
		phone_number:"String",
		alternate_phone_number:"String",
		expected_delivery_time:"String",
		average_price_for_one:"Int",
		average_price_for_two:"Int",
		delivery_charge:"Int",
		min_order_value:"Int",
		max_order_value:"Int",
		packaging_charge:"Int",
		rating:"Float",
		is_open:"Boolean",
		is_featured:"Boolean",
		is_available_for_delivery:"Boolean",
		is_available_for_pickup:"Boolean",
		is_veg_only:"Boolean",
		opening_time:"String",
		closing_time:"String",
		special_opening_time:"String",
		special_closing_time:"String",
		average_preparation_time:"String",
		slug:"String",
		short_description:"String",
		full_description:"String",
		gst_number:"String",
		fssai_license_number:"String",
		service_radius_km:"Float",
		approval_status:"String",
		approval_notes:"String",
		cancellation_policy:"String",
		external_integration_id:"String",
		timezone:"String",
		country:"String",
		state:"String",
		city:"String",
		zip_code:"String",
		landmark:"String",
		block_floor_number:"Int",
		nearby_landmark:"String",
		created_at:"Date",
		updated_at:"Date",
		deleted_at:"Date",
		created_by:"Int",
		updated_by:"Int",
		deleted_by:"Int"
	},
	RestaurantResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Restaurant"
	},
	BranchesResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Branches"
	},
	Branches:{
		id:"Int",
		description:"String",
		restaurant_id:"Int",
		owner_id:"Int",
		manager_id:"Int",
		location:"String",
		longitude:"Float",
		latitude:"Float",
		image:"String",
		email:"String",
		phone_number:"String",
		alternate_phone_number:"String",
		expected_delivery_time:"String",
		average_price_for_one:"Int",
		average_price_for_two:"Int",
		delivery_charge:"Int",
		min_order_value:"Int",
		max_order_value:"Int",
		packaging_charge:"Int",
		rating:"Float",
		is_open:"Boolean",
		is_featured:"Boolean",
		is_available_for_delivery:"Boolean",
		is_available_for_pickup:"Boolean",
		is_veg_only:"Boolean",
		opening_time:"String",
		closing_time:"String",
		special_opening_time:"String",
		special_closing_time:"String",
		average_preparation_time:"String",
		slug:"String",
		short_description:"String",
		full_description:"String",
		gst_number:"String",
		fssai_license_number:"String",
		service_radius_km:"Float",
		approval_status:"String",
		approval_notes:"String",
		cancellation_policy:"String",
		external_integration_id:"String",
		timezone:"String",
		country:"String",
		state:"String",
		city:"String",
		zip_code:"String",
		landmark:"String",
		block_floor_number:"Int",
		nearby_landmark:"String",
		created_at:"Date",
		updated_at:"Date",
		deleted_at:"Date",
		created_by:"Int",
		updated_by:"Int",
		deleted_by:"Int",
		restaurant:"Restaurant",
		owner:"User",
		manager:"User"
	},
	BranchByIdResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"RBranch"
	},
	getBranchesByRestaurantIdResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"RBranch"
	},
	CategoryByIdResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Category"
	},
	Category:{
		id:"Int",
		name:"String",
		slug:"String",
		short_description:"String",
		long_description:"String",
		image:"String",
		banner_image:"String",
		icon:"String",
		display_order:"Int",
		is_featured:"Boolean",
		is_active:"Boolean",
		seo_title:"String",
		seo_description:"String",
		seo_keywords:"String",
		created_at:"Date",
		updated_at:"Date",
		deleted_at:"Date",
		created_by:"Int",
		updated_by:"Int",
		deleted_by:"Int"
	},
	CategoryListResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"categoryList"
	},
	categoryList:{
		count:"Int",
		rows:"Category"
	},
	SubCategoriesListResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"subCategories"
	},
	subCategories:{
		count:"Int",
		rows:"SubCategory"
	},
	SubCategory:{
		id:"Int",
		category_id:"Int",
		name:"String",
		slug:"String",
		short_description:"String",
		long_description:"String",
		image:"String",
		banner_image:"String",
		icon:"String",
		display_order:"Int",
		is_featured:"Boolean",
		is_active:"Boolean",
		seo_title:"String",
		seo_description:"String",
		seo_keywords:"String",
		created_at:"Date",
		updated_at:"Date",
		deleted_at:"Date",
		created_by:"Int",
		updated_by:"Int",
		deleted_by:"Int"
	},
	SubCategoryByIdResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"SubCategory"
	},
	dishListResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"dishList"
	},
	dishList:{
		count:"Int",
		rows:"Dish"
	},
	Dish:{
		id:"Int",
		restaurant_id:"Int",
		branch_id:"Int",
		category_id:"Int",
		subcategory_id:"Int",
		name:"String",
		slug:"String",
		description:"String",
		image:"String",
		banner_image:"String",
		price:"Float",
		original_price:"Float",
		currency:"String",
		discount_percentage:"Float",
		is_available:"Boolean",
		is_veg:"Boolean",
		is_customizable:"Boolean",
		spicy_level:"String",
		preparation_time_minutes:"Int",
		dietary_tags:"String",
		ingredients:"String",
		availability_start_time:"Time",
		availability_end_time:"Time",
		stock_quantity:"Int",
		min_order_qty:"Int",
		max_order_qty:"Int",
		rating:"Float",
		approval_status:"String",
		rejection_reason:"String",
		created_at:"Date",
		updated_at:"Date",
		deleted_at:"Date",
		parent_dish_id:"Int",
		long_description:"String",
		gallery_images:"String",
		video_url:"String",
		tags:"String",
		price_unit:"String",
		tax_percentage:"Float",
		tax_inclusive:"Boolean",
		service_charge_percentage:"Float",
		packaging_charge:"Float",
		discount_type:"String",
		discount_amount:"Float",
		discount_amount_upto:"Float",
		discount_start_time:"Date",
		discount_end_time:"Date",
		discount_max_quantity:"Int",
		discount_min_quantity:"Int",
		discount_max_quantity_per_user:"Int",
		discount_min_quantity_per_user:"Int",
		discount_max_quantity_per_order:"Int",
		discount_min_quantity_per_order:"Int",
		discount_applies_with_coupon:"Boolean",
		promo_code_applicable:"Boolean",
		availability_days:"String",
		blackout_dates:"String",
		preorder_available:"Boolean",
		preorder_hours:"Int",
		delivery_eta_minutes:"Int",
		delivery_buffer_minutes:"Int",
		available_portions:"Int",
		allergen_info:"JSONObject",
		allergens:"String",
		meal_time_tags:"String",
		featured:"Boolean",
		is_featured:"Boolean",
		is_new:"Boolean",
		is_popular:"Boolean",
		is_recommended:"Boolean",
		is_best_seller:"Boolean",
		is_chef_special:"Boolean",
		is_available_for_delivery:"Boolean",
		is_available_for_pickup:"Boolean",
		is_available_for_dine_in:"Boolean",
		is_available_for_takeaway:"Boolean",
		language_tags:"JSONObject",
		regional_exclusivity:"String",
		cuisine_type:"String",
		name_translations:"JSONObject",
		description_translations:"JSONObject",
		seo_title:"String",
		seo_description:"String",
		promo_tags:"String",
		share_url:"String",
		total_reviews:"Int",
		average_rating:"Float",
		total_orders:"Int",
		reorder_rate:"Float",
		cart_additions:"Int",
		view_count:"Int",
		conversion_rate:"Float",
		user_likes_count:"Int",
		order_count:"Int",
		reorder_probability:"Float",
		smart_tags:"String",
		kitchen_station:"String",
		priority_order:"Int",
		shelf_life_hours:"Int",
		is_ready_to_eat:"Boolean",
		fssai_info:"JSONObject",
		auto_tags:"String",
		restaurant:"Restaurant",
		branch:"RBranch",
		category:"Category",
		subcategory:"SubCategory",
		created_by:"User",
		ingredients_options:"DIngredients",
		customization_groups:"DCustomization"
	},
	Time: `scalar.Time` as const,
	DIngredients:{
		id:"Int",
		dish_id:"Int",
		name:"String",
		image_url:"String",
		has_options:"Boolean",
		created_at:"Date",
		updated_at:"Date",
		options:"DIOption"
	},
	DIOption:{
		id:"Int",
		name:"String",
		price:"Float",
		ingredient_id:"Int",
		description:"String",
		image_url:"String",
		created_at:"Date",
		updated_at:"Date"
	},
	DCustomization:{
		id:"Int",
		dish_id:"Int",
		title:"String",
		is_required:"Boolean",
		min_selection:"Int",
		max_selection:"Int",
		selection_type:"String",
		order:"Int",
		options:"IDCOption"
	},
	IDCOption:{
		id:"Int",
		customization_id:"Int",
		title:"String",
		price:"Int",
		order:"Int"
	},
	getDishByIdResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Dish"
	},
	getDishByCategoriesTypeResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"getDishByCategoriesData"
	},
	getDishByCategoriesData:{
		count:"Int",
		rows:"getDishByCategoriesRows"
	},
	getDishByCategoriesRows:{
		id:"Int",
		name:"String",
		dishes:"Dish"
	},
	RootMutation:{
		createRole:"createRoleResponse",
		updateRole:"updateRoleResponse",
		deleteRole:"Role",
		createUser:"CreateUserResponse",
		updateUser:"UpdateUserResponse",
		deleteUser:"DeleteUserResponse",
		login:"LoginResponse",
		register:"RegisterResponse",
		createRestaurant:"RestaurantResponse",
		updateRestaurant:"RestaurantResponse",
		createCategory:"createCategoryResponse",
		updateCategory:"updateCategoryResponse",
		deleteCategory:"deleteCategoryResponse",
		createSubcategory:"createSubcategoryResponse",
		updateSubcategory:"updateSubcategoryResponse",
		deleteSubcategory:"deleteSubcategoryResponse",
		createBranch:"createBranchResponse",
		updateBranch:"updateBranchResponse",
		deleteBranch:"deleteBranchResponse",
		createDish:"createDishResponse",
		updateDish:"updateDishResponse"
	},
	createRoleResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Role"
	},
	updateRoleResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Role"
	},
	CreateUserResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"User"
	},
	UpdateUserResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"User"
	},
	DeleteUserResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String"
	},
	LoginResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		token:"String",
		data:"User"
	},
	RegisterResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		token:"String"
	},
	createCategoryResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Category"
	},
	updateCategoryResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Category"
	},
	deleteCategoryResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String"
	},
	createSubcategoryResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"SubCategory"
	},
	updateSubcategoryResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"SubCategory"
	},
	deleteSubcategoryResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String"
	},
	createBranchResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"RBranch"
	},
	updateBranchResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"RBranch"
	},
	deleteBranchResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"RBranch"
	},
	createDishResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Dish"
	},
	updateDishResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Dish"
	},
	ID: `scalar.ID` as const
}

export const Ops = {
query: "RootQuery" as const,
	mutation: "RootMutation" as const
}