/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	RootQuery:{
		getRoleById:{

		},
		restaurant:{

		},
		getBranchById:{

		},
		getBranchByRestaurantId:{

		},
		getCategoryById:{

		},
		subCategoriesList:{

		},
		getSubcategoryById:{

		}
	},
	Date: `scalar.Date` as const,
	JSONObject: `scalar.JSONObject` as const,
	RootMutation:{
		createOrUpdateRole:{
			permissions:"JSONObject"
		},
		deleteRole:{

		},
		createUser:{
			dob:"Date",
			last_login_at:"Date",
			otp_expiry:"Date"
		},
		updateUser:{
			dob:"Date",
			last_login_at:"Date",
			otp_expiry:"Date"
		},
		deleteUser:{

		},
		login:{

		},
		register:{
			dob:"Date",
			last_login_at:"Date",
			otp_expiry:"Date"
		},
		createRestaurant:{

		},
		updateRestaurant:{
			created_at:"Date",
			updated_at:"Date",
			deleted_at:"Date"
		},
		createCategory:{
			created_at:"Date",
			updated_at:"Date",
			deleted_at:"Date"
		},
		updateCategory:{
			created_at:"Date",
			updated_at:"Date",
			deleted_at:"Date"
		},
		deleteCategory:{

		},
		createSubcategory:{

		},
		updateSubcategory:{
			created_at:"Date",
			updated_at:"Date",
			deleted_at:"Date"
		},
		deleteSubcategory:{

		},
		createBranch:{
			created_at:"Date",
			updated_at:"Date",
			deleted_at:"Date"
		},
		updateBranch:{
			created_at:"Date",
			updated_at:"Date",
			deleted_at:"Date"
		},
		deleteBranch:{

		},
		createCDeal:{
			created_at:"Date",
			updated_at:"Date"
		},
		deleteCDeals:{

		},
		createRDeal:{
			created_at:"Date",
			updated_at:"Date"
		},
		deleteRDeals:{

		},
		createRBDeal:{
			created_at:"Date",
			updated_at:"Date"
		},
		deleteRBDeal:{

		},
		createDish:{
			dietary_tags:"JSONObject",
			availability_start_time:"Time",
			availability_end_time:"Time",
			created_at:"Date",
			updated_at:"Date",
			deleted_at:"Date",
			ingredients_options:"IngredientInput"
		}
	},
	Time: `scalar.Time` as const,
	IngredientInput:{
		created_at:"Date",
		updated_at:"Date",
		options:"DIOptionInput"
	},
	DIOptionInput:{

	},
	ID: `scalar.ID` as const
}

export const ReturnTypes: Record<string,any> = {
	RootQuery:{
		getAllRoles:"RolesResponse",
		getRoleById:"RoleResponse",
		usersList:"UsersResponse",
		getProfile:"getProfileResponse",
		RestaurantList:"RestaurantsResponse",
		restaurant:"RestaurantResponse",
		RBranchList:"BranchesResponse",
		getBranchById:"BranchByIdResponse",
		getBranchByRestaurantId:"getBranchesByRestaurantIdResponse",
		getCategoryById:"CategoryByIdResponse",
		categoryList:"CategoryListResponse",
		subCategoriesList:"SubCategoriesListResponse",
		getSubcategoryById:"SubCategoryByIdResponse"
	},
	RolesResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Role"
	},
	Role:{
		id:"Int",
		created_at:"Date",
		deleted_at:"Date",
		updated_at:"Date",
		name:"String",
		permissions:"JSONObject"
	},
	Date: `scalar.Date` as const,
	JSONObject: `scalar.JSONObject` as const,
	RoleResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Role"
	},
	UsersResponse:{
		message:"String",
		data:"Users"
	},
	Users:{
		count:"Int",
		rows:"User"
	},
	User:{
		id:"Int",
		username:"String",
		phone:"String",
		gender:"String",
		dob:"Date",
		aadhar_card:"String",
		pan_card:"String",
		voter_id:"String",
		first_name:"String",
		last_name:"String",
		email:"String",
		password:"String",
		role_id:"Int",
		is_active:"Boolean",
		is_verified:"Boolean",
		profile_picture:"String",
		address:"String",
		city:"String",
		state:"String",
		country:"String",
		zip_code:"Int",
		last_login_at:"Date",
		login_count:"Int",
		device_token:"String",
		wallet_balance:"Float",
		referral_code:"Int",
		referred_by:"Int",
		otp_code:"Int",
		otp_expiry:"Date",
		blocked_reason:"String",
		language_preference:"String",
		created_at:"Date",
		updated_at:"Date",
		deleted_at:"Date",
		created_by:"Int",
		updated_by:"Int",
		deleted_by:"Int",
		terms_conditions_accepted:"Boolean",
		role:"Role"
	},
	getProfileResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"User"
	},
	RestaurantsResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Restaurant"
	},
	Restaurant:{
		id:"Int",
		owner_id:"Int",
		name:"String",
		slug:"String",
		description:"String",
		image:"String",
		email:"String",
		phone_number:"String",
		alternate_phone_number:"String",
		website_url:"String",
		facebook_url:"String",
		instagram_url:"String",
		gst_number:"String",
		status:"String",
		rejection_reason:"String",
		fssai_license_number:"String",
		is_chain:"Boolean",
		founded_year:"String",
		total_branches:"Int",
		cuisine_types:"String",
		tags:"String",
		average_rating:"Float",
		total_reviews:"Int",
		is_verified:"Boolean",
		approval_status:"String",
		approval_notes:"String",
		timezone:"String",
		external_integration_id:"Int",
		priority_order:"Int",
		visibility_status:"String",
		cancellation_policy:"String",
		created_at:"Date",
		updated_at:"Date",
		deleted_at:"Date",
		created_by:"Int",
		updated_by:"Int",
		deleted_by:"Int",
		account_number:"String",
		upi_id:"String",
		swift_code:"String",
		bank_name:"String",
		bank_branch:"String",
		ifsc_code:"String",
		account_holder_name:"String",
		branches:"RBranch",
		branch:"RBranch",
		owner:"User"
	},
	RBranch:{
		id:"Int",
		restaurant_id:"Int",
		manager_id:"Int",
		location:"String",
		longitude:"Float",
		latitude:"Float",
		image:"String",
		email:"String",
		phone_number:"String",
		alternate_phone_number:"String",
		expected_delivery_time:"Int",
		average_price_for_one:"Int",
		average_price_for_two:"Int",
		delivery_charge:"Int",
		min_order_value:"Int",
		max_order_value:"Int",
		packaging_charge:"Int",
		rating:"Float",
		is_open:"Boolean",
		is_featured:"Boolean",
		is_available_for_delivery:"Boolean",
		is_available_for_pickup:"Boolean",
		is_veg_only:"Boolean",
		opening_time:"String",
		closing_time:"String",
		special_opening_time:"String",
		special_closing_time:"String",
		average_preparation_time:"Int",
		slug:"String",
		short_description:"String",
		full_description:"String",
		gst_number:"String",
		fssai_license_number:"String",
		service_radius_km:"Float",
		approval_status:"String",
		approval_notes:"String",
		cancellation_policy:"String",
		external_integration_id:"String",
		timezone:"String",
		created_at:"Date",
		updated_at:"Date",
		deleted_at:"Date",
		created_by:"Int",
		updated_by:"Int",
		deleted_by:"Int"
	},
	RestaurantResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Restaurant"
	},
	BranchesResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"RBranch"
	},
	BranchByIdResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"RBranch"
	},
	getBranchesByRestaurantIdResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"RBranch"
	},
	CategoryByIdResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Category"
	},
	Category:{
		id:"Int",
		name:"String",
		slug:"String",
		short_description:"String",
		long_description:"String",
		image:"String",
		banner_image:"String",
		icon:"String",
		display_order:"String",
		is_featured:"Boolean",
		is_active:"Boolean",
		seo_title:"String",
		seo_description:"String",
		seo_keywords:"String",
		created_at:"Date",
		updated_at:"Date",
		deleted_at:"Date",
		created_by:"Int",
		updated_by:"Int",
		deleted_by:"Int"
	},
	CategoryListResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Category"
	},
	SubCategoriesListResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"SubCategory"
	},
	SubCategory:{
		id:"Int",
		category_id:"Int",
		name:"String",
		slug:"String",
		short_description:"String",
		long_description:"String",
		image:"String",
		banner_image:"String",
		icon:"String",
		display_order:"Int",
		is_featured:"Boolean",
		is_active:"Boolean",
		seo_title:"String",
		seo_description:"String",
		seo_keywords:"String",
		created_at:"Date",
		updated_at:"Date",
		deleted_at:"Date",
		created_by:"Int",
		updated_by:"Int",
		deleted_by:"Int"
	},
	SubCategoryByIdResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"SubCategory"
	},
	RootMutation:{
		createOrUpdateRole:"Role",
		deleteRole:"Role",
		createUser:"CreateUserResponse",
		updateUser:"UpdateUserResponse",
		deleteUser:"DeleteUserResponse",
		login:"LoginResponse",
		register:"RegisterResponse",
		createRestaurant:"RestaurantResponse",
		updateRestaurant:"RestaurantResponse",
		createCategory:"createCategoryResponse",
		updateCategory:"updateCategoryResponse",
		deleteCategory:"deleteCategoryResponse",
		createSubcategory:"createSubcategoryResponse",
		updateSubcategory:"updateSubcategoryResponse",
		deleteSubcategory:"deleteSubcategoryResponse",
		createBranch:"createBranchResponse",
		updateBranch:"updateBranchResponse",
		deleteBranch:"deleteBranchResponse",
		createCDeal:"createCDealResponse",
		deleteCDeals:"deleteCDealResponse",
		createRDeal:"createRDealResponse",
		deleteRDeals:"deleteRDealResponse",
		createRBDeal:"createRBDealResponse",
		deleteRBDeal:"deleteRBDealResponse",
		createDish:"createDishResponse"
	},
	CreateUserResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"User"
	},
	UpdateUserResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"User"
	},
	DeleteUserResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String"
	},
	LoginResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		token:"String"
	},
	RegisterResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		token:"String"
	},
	createCategoryResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Category"
	},
	updateCategoryResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Category"
	},
	deleteCategoryResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String"
	},
	createSubcategoryResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"SubCategory"
	},
	updateSubcategoryResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"SubCategory"
	},
	deleteSubcategoryResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String"
	},
	createBranchResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"RBranch"
	},
	updateBranchResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"RBranch"
	},
	deleteBranchResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"RBranch"
	},
	createCDealResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"CDeals"
	},
	CDeals:{
		id:"Int",
		deal_id:"Int",
		category_id:"Int",
		created_at:"Date",
		updated_at:"Date"
	},
	deleteCDealResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"CDeals"
	},
	createRDealResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"RDeals"
	},
	RDeals:{
		id:"Int",
		deal_id:"Int",
		restaurant_id:"Int",
		created_at:"Date",
		updated_at:"Date"
	},
	deleteRDealResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"RDeals"
	},
	createRBDealResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"RBDeals"
	},
	RBDeals:{
		id:"Int",
		deal_id:"Int",
		rbranch_id:"Int",
		created_at:"Date",
		updated_at:"Date"
	},
	deleteRBDealResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"RBDeals"
	},
	createDishResponse:{
		status:"Int",
		success:"Boolean",
		isToast:"Boolean",
		isError:"Boolean",
		message:"String",
		data:"Dish"
	},
	Dish:{
		id:"Int",
		restaurant_id:"Int",
		branch_id:"Int",
		category_id:"Int",
		subcategory_id:"Int",
		name:"String",
		slug:"String",
		description:"String",
		image:"String",
		banner_image:"String",
		price:"Float",
		original_price:"Float",
		currency:"String",
		discount_percentage:"Float",
		is_available:"Boolean",
		is_veg:"Boolean",
		is_customizable:"Boolean",
		spicy_level:"String",
		preparation_time_minutes:"Int",
		dietary_tags:"JSONObject",
		ingredients:"String",
		availability_start_time:"Time",
		availability_end_time:"Time",
		stock_quantity:"Int",
		min_order_qty:"Int",
		max_order_qty:"Int",
		rating:"Float",
		approval_status:"String",
		rejection_reason:"String",
		created_at:"Date",
		updated_at:"Date",
		deleted_at:"Date",
		restaurant:"Restaurant",
		branch:"RBranch",
		category:"Category",
		subcategory:"SubCategory"
	},
	Time: `scalar.Time` as const,
	ID: `scalar.ID` as const
}

export const Ops = {
query: "RootQuery" as const,
	mutation: "RootMutation" as const
}